---
- name: check if nginx is installed.
  stat:
    path: /usr/sbin/nginx
  register: nginx_bin

- name: copy nginx repo
  copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
  when: not nginx_bin.stat.exists

#- name: enable nginx-mainline
#  command: yum-config-manager --enable nginx-mainline
#  when: not nginx_bin.stat.exists

- name: ensure nginx is installed.
  dnf:
    name: nginx
    state: present
  when: not nginx_bin.stat.exists

- name: copy nginx default config
  copy:
    src: "{{ inventory_hostname }}/default.conf"
    dest: /etc/nginx/conf.d/default.conf
  when: not nginx_bin.stat.exists

- name: ensure nginx is started and enabled to start at boot.
  service:
    name: nginx
    state: started
    enabled: yes
  when: not nginx_bin.stat.exists
