---
- name: check if Composer is installed.
  stat:
    path: /usr/bin/composer
  register: composer_bin

- name: download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
  when: not composer_bin.stat.exists

- name: run Composer installer.
  command: php /tmp/composer-installer.php --install-dir=/usr/bin --filename=composer
  args:
    creates: /usr/bin/composer
  when: not composer_bin.stat.exists
